models/models.py
import psycopg2
import bcrypt

class DbManager:
	def __init__(self):
		self.conn = psycopg2.connect(
			dbname = "chess",
			user = "backslash057",
			password = "root"
		)

		self.init_tables()

	def init_tables(self):
		cursor = self.conn.cursor()
		cursor.execute("""
			CREATE TABLE IF NOT EXISTS users(id serial PRIMARY KEY,
				username VARCHAR(20), password VARCHAR(64));
			TRUNCATE TABLE users;
			CREATE TABLE IF NOT EXISTS banned_passwords(pwd VARCHAR(64));
			TRUNCATE TAbLE banned_passwords;
			""")
		self.conn.commit()
		cursor.close()

	def password_valid(self, password):
		cursor = self.conn.cursor()

		cursor.execute("SELECT * FROM banned_passwords WHERE pwd=%s", (password,))

		num_lines = cursor.rowcount
		cursor.close()

		if num_lines != 0:
			return False
		return True


	def username_in_use(self, username):
		cursor = self.conn.cursor()

		cursor.execute("SELECT * FROM users WHERE username=%s", (username,))

		num_lines = cursor.rowcount
		cursor.close()
		
		if num_lines == 0:
			return False
		return True


	def save_user(self, username, password):
		# random_salt = bcrypt.gensalt()
		# hashpwd = bcrypt.hashpw(password.encode("utf-8"), random_salt)
		# hashpwd = hashpwd.decode("utf-8")

		cursor = self.conn.cursor()
		sql = "INSERT INTO users(username, password) VALUES (%s, %s);"
		
		cursor.execute(sql, (username, password))
		self.conn.commit()

		cursor.close()

	def valid_user(self, username, password):
		cursor = self.conn.cursor()

		# random_salt = bcrypt.gensalt()
		# hashpwd = bcrypt.hashpw(password.encode("utf-8"), random_salt)
		# hashpwd = hashpwd.decode("utf-8")
		# print(hashpwd)

		cursor.execute("SELECT * FROM users WHERE username=%s AND password=%s", (username, password))

		if cursor.rowcount == 0:
			return False
		return True


	def close(self):
		self.conn.close()


dbManager = DbManager()

app.py
from flask import Flask

from views.home import home
from views.auth import auth


app = Flask(__name__)
app.secret_key = "b524f20474380e639312586bf20ef9ab95e2b5395dbe405efba2949e7870f7f3"


app.register_blueprint(home)
app.register_blueprint(auth)
 

@app.route("/friendly")
def friendly():
	return ""

@app.route("/computer")
def computer():
	return ""


if __name__ == "__main__":
	app.run(debug=True)

controllers/chess.py
class Game:
    def __init__(self, player1):
        self.colors = ["white", "black"]
        self.players = [player1]

        self.full = False
        self.current_player = 0

    def is_a_player(self, p):
        for player in self.players:
            if player == p:
                return True
            print(f"player {p} found")
        return False

    def verify_move(self, move):
        pass

    def play(self, id, move):
        return False
        

def create_or_get_game(player):
    waiting_game = None
    for game_id in games:
        if player in games[game_id].players:
            return game_id
        if not games[game_id].full and waiting_game == None:
            waiting_game = game_id
        
    
    if waiting_game is not None:
        games[waiting_game].players.append(player)
        games[waiting_game].full = True
        return waiting_game

    newGame = Game(player)
    id = len(games)
    games[id] = newGame
    return id


games = {}

started_games = {}

views/auth.py
from flask import Blueprint, render_template, session


auth = Blueprint("auth", __name__)

@auth.route("/login", methods=["GET"])
def login():
	return render_template("login.html")

@auth.route("/login", methods=["POST"])
def login_post():
	try:
		datas = request.get_json()
	except: return "Bad request", 403
	# search -> http response on bad request body(json required)

	username = datas.get('username', '').strip()
	password = datas.get('password', '').strip()

	if not username:
		return jsonify({"success": False, "message": "Username not defined."})

	if not password:
		return jsonify({"success": False, "message": "Password not defined."})

	if not dbManager.valid_user(username, password):
		return jsonify({"success": False, "message": "Invalid username or password"})
	
	session['username'] = username
	print(session)
	return jsonify({"success": True})


@auth.route("/signup", methods=["GET"])
def signup():
	return render_template("signup.html")


@auth.route("/signup", methods=["POST"])
def signup_post():
	datas = request.get_json()

	username = datas.get('username', '').strip()
	password = datas.get('password', '').strip()

	if not username:
		return jsonify({"success": False, "message": "Username not defined."})
	if len(username) < 4:
		return jsonify({"success": False, "message": "Too short username."})

	valid_chars = ascii_letters + digits + "_"
	for char in set(username):
		if char not in valid_chars:
			return jsonify({'success': False, "message": "Special characters forbidded in username."})

	if dbManager.username_in_use(username):
		return jsonify({"success": False, "message": "Username already in use."})

	if not password:
		return jsonify({"success": False, "message": "Password not defined."})

	if len(password) < 8:
		return jsonify({"success": False, "message": "Too short password."})
	
	if not dbManager.password_valid(password):
		return jsonify({"succes": False, "message": "Insecure password."})


	dbManager.save_user(username, password)
	session["username"] = username
	return jsonify({"success": True})

views/home.py
from flask import Blueprint, render_template, session


home = Blueprint("home", __name__)

@home.route("/")
def index():
	print(session)
	return render_template("index.html", session=session)

views/multiplayer.py
from flask import Blueprint, session, redirect, url_for

multiplayer = Blueprint("multiplayer", __name__)


@multiplayer.rout("/game", mathods=["GET"])
def multiplayer():
	if 'username' not in session:
		return redirect(url_for('/login'))

	elif 'id' not  in request.args:
		username = session['username']
		id = chess.create_or_get_game(username)
		return redirect(url_for('game', id=id))
	else:
		id = request.args['id']
		return render_template("game.html", session=session, gameId=id)


@multiplayer.route("/game", methods=["POST"])
def multiplayer_post():
	data = request.get_json()

	message = data.get('mesage')
	return jsonify({"message": "message recu"})

templates/game.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chess game</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/game.css')}}">
</head>
<body>
    <div class="game">
        <div class="player1"></div>
        <div class="container" style="background-image: url('{{ url_for('static', filename='imgs/numbers.svg') }}');"></div>
        <div class="player2"></div>
    </div>
    <div class="chat">
        <div class="chat-head">Chat</div>
        <div class="chat-messages">
            <div class="message">
                <span class="author">eddy: </span>
                <span class="msg">Hello world</span>
            </div>
        </div>
        <input type="text" class="chat-input">
    </div>


    <script src=" {{ url_for('static', filename='js/game.js') }}"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chess - Play chess on the #1 site</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='imgs/favicon.ico') }}" type="image/x-icon">
</head>
<body>
    <nav class="menu">
        <img class="chess-logo" src="static/imgs/chess-logo.svg">
        {% if 'username' in session %}
            <div class="username-box">
                <img src="{{ url_for('static', filename='imgs/user.svg')}}" alt=" logo de {{ session['username']}}" class="user-logo">
                <span class="username">{{ session['username'] }}</span>
            </div>
           
        {% else %}
            <div class="nav-links">
                <a href="{{ url_for('auth.signup')}}" class="signup nav-button">Sign Up</a>
                <a href="{{ url_for('auth.login')}}" class="login nav-button button-green">Log In</a>
            </div>
        {% endif %}
    </nav>
    <main class="content">
        <div class="container">
            <img src="static/imgs/chess.png" alt="Chess game image" class="chess-game">
            <div class="action">
                <div class="description">
                    <div>Play Chess</div>
                    <div>Online</div>
                    <div>on the #1 site!</div>
                </div>
                <ul class="game-stats">
                    <li class="game-stats-item">
                        <div class="today-games games-count">0</div>
                        <div class="stat-label">Games today</div></li>
                    <li class="game-stats-item">
                        <div class="current-games games-count">0</div>
                        <div class="stat-label">Playing now</div>
                    </li>
                </ul>
                <div class="action-buttons">
                    <a href="{{ url_for('game')}}"  class="online-game game-button game-button-green">
                        <div class="game-button-image-container">
                            <img src="{{ url_for('static', filename='imgs/online-game.svg')}}" class="game-button-image">
                        </div>
                        <div class="game-button-text" href="#">
                            <div class="game-title">Play online</div>
                            <div class="game-description">Play with womeone at your level</div>
                        </div>
                    </a>
                    <a href="{{ url_for('friendly')}}" class="online-game game-button">
                        <div class="game-button-image-container">
                            <img src="{{ url_for('static', filename='imgs/friendly-game.svg')}}" class="game-button-image">
                        </div>
                        <div class="game-button-text">
                            <div class="game-title">Play with a friend</div>
                            <div class="game-description">Challenge a friend on a quick game</div>
                        </div>
                    </a>
                    <a href="{{ url_for('computer')}}" class="computer-game game-button">
                        <div class="game-button-image-container">
                            <img src="{{ url_for('static', filename='imgs/computer-game.svg')}}" class="game-button-image">
                        </div>
                        <div class="game-button-text">
                            <div class="game-title">Play computer</div>
                            <div class="game-description">Play vs customizable training bots</div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </main>
    <footer></footer>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Chess - Login</title>
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/auth.css')}}">
</head>
<body>
	<img class="bg" src="{{ url_for('static', filename='imgs/chessboard-background.png') }}">
	<div class="login-header">
		<img src="{{ url_for('static', filename='imgs/chess-logo.svg')}}">
	</div>
	<form class="form" method="POST" action="">
		<div class="output"></div>
		<div class="form-input">
			<label for="username">Username</label>
			<input type="text" name="username" id="username">
		</div>
		<div class="form-input">
			<label for="password">Password</label>
			<input type="password" name="password" id="password">
		</div>
		<div class="remember-check">
			<input type="checkbox" name="remember" id="remember">
			<label for="remember">Remember me</label>
		</div>
		<div class="submit-box">
			<input class="submit" type="submit" id="submit" value="Log In" />
			<div class="alternative">No account yet? <a href="{{ url_for('signup') }}">Sign Up</a></div>
		</div>
	</form>

	<script type="text/javascript" src="{{ url_for('static', filename='js/login.js') }}"></script>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Chess - Login</title>
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/auth.css')}}">
</head>
<body>
	<img class="bg" src="{{ url_for('static', filename='imgs/chessboard-background.png') }}">
	<div class="login-header">
		<img src="{{ url_for('static', filename='imgs/chess-logo.svg')}}">
	</div>
	<form class="form" method="POST" action="">
		<div class="output"></div>
		<div class="form-input">
			<label for="username">Username</label>
			<input type="text" name="username" id="username">
		</div>
		<div class="form-input">
			<label for="password">Password</label>
			<input type="password" name="password" id="password">
		</div>
		<div class="remember-check">
			<input type="checkbox" name="remember" id="remember">
			<label for="remember">Remember me</label>
		</div>
		<div class="submit-box">
			<input class="submit" type="submit" id="submit" value="Sign Up" />
			<div class="alternative">Already registered? <a href="{{ url_for('login') }}">Log In</a></div>
		</div>
	</form>
	<script type="text/javascript" src="{{ url_for('static', filename='js/signup.js') }}"></script>
</body>
</html>

templates/test.html
<!DOCTYPE html>
<html>
<head>
  <title>SSE Client</title>
</head>
<body>
  <h1>SSE Client</h1>
  <div id="events"></div>
  <script>
    const eventSource = new EventSource('/events');

    eventSource.onmessage = function(event) {
      const newElement = document.createElement("div");
      newElement.innerHTML = "Event: " + event.data;
      document.getElementById('events').appendChild(newElement);
    };
  </script>
</body>
</html>